# Google Gemini API Configuration
gemini:
  # Model name
  model_name: 'gemini-1.5-pro'
  
  # Generation parameters
  temperature: 0.0
  top_p: 0.95
  top_k: 40
  max_output_tokens: 1024

# Application Configuration
app:
  # Maximum number of examples to process in a single request (0 for unlimited)
  max_examples: 0
  
  # Enable caching of model responses (to avoid redundant API calls)
  enable_caching: true
  
  # Debug mode (more verbose logging)
  debug: true
